---
title: "Test Run Control Metacommunities"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
```

```{r}
# Libraries

library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(purrr)
library(tibble)
library(ggtern)
library(corrplot)

library(HMSC)
library(coda)
```

```{r}
# Load data 
resetarits_data <- read.table(here::here("data", "Resetarits&al2018FinalData.txt"))
head(resetarits_data)

resetarits_data %>%
  dplyr::filter(., type == "E") %>%
  dplyr::select(., landscape, ends_with("_density")) -> ctrl_density

resetarits_data %>%
  dplyr::filter(., type == "E") %>%
  dplyr::select(., landscape, habitat.bi, age) -> ctrl_env

ctrl_mem <- readRDS("paper/ctrl_mem.RDS")
```

```{r}
# Functions

# Plot Species
species_plot <- function(data, plotMain = NULL, colorVar = NULL, colorLegend = "none"){
  data %>%
    ggtern(aes(x = env, z = spa, y = codist, size = r2)) +
    geom_point(aes_string(color = colorVar), alpha = 0.8) +
    scale_T_continuous(limits=c(0,1.0),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    scale_L_continuous(limits=c(0.0,1),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    scale_R_continuous(limits=c(0.0,1.0),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    labs(title = plotMain,
         x = "E",
         xarrow = "Environment",
         y = "C",
         yarrow = "Co-Distribution",
         z = "S",
         zarrow = "Spatial Autocorrelation") +
    theme_light() +
    theme_showarrows() +
    #scale_colour_brewer(palette = "Set1") +
    #scale_colour_brewer(palette = "Spectral") +
    #scale_color_viridis_d() +
    scale_size_area(limits = c(0,1), breaks = seq(0,1,0.2)) +
    guides(color = guide_legend(colorLegend, order = 2),
           size = guide_legend(title = expression(R^2), order = 1)) +
    theme(panel.grid = element_line(color = "darkgrey"),
          axis.title = element_text(size = 8))
}

# Plot Sites

sites_plot <- function(data, plotMain = NULL, colorVar = NULL, colorLegend = "none"){
  data %>%
    ggtern(aes(x = env, z = spa, y = codist, size = r2)) +
    geom_point(aes_string(color = colorVar), alpha = 0.6) +
    scale_T_continuous(limits=c(0,1.0),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    scale_L_continuous(limits=c(0.0,1),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    scale_R_continuous(limits=c(0.0,1.0),
                       breaks=seq(0,1,by=0.1),
                       labels=seq(0,1,by=0.1)) +
    labs(title = plotMain,
         x = "E",
         xarrow = "Environment",
         y = "C",
         yarrow = "Co-Distribution",
         z = "S",
         zarrow = "Spatial Autocorrelation") +
    theme_light() +
    theme_showarrows() +
    #scale_colour_brewer(palette = "Set1") +
    #scale_colour_brewer(palette = "Spectral") +
    #scale_color_viridis_d() +
    scale_size_area(limits = c(0, 0.003), breaks = seq(0, 0.003, 0.0005)) +
    guides(color = guide_colorbar(colorLegend),
           size = guide_legend(title = expression(R^2))) +
    theme(panel.grid = element_line(color = "darkgrey"),
          axis.title = element_text(size = 8))
}

# Interactions plot

interaction_plot <- function(model, corTitle = NULL){

  assoMat <- corRandomEff(model)
  siteMean <- apply(assoMat[ , , , 1], 1:2, mean)

  siteDrawCol <- matrix(NA, nrow = nrow(siteMean), ncol = ncol(siteMean))
  siteDrawCol[which(siteMean > 0.4, arr.ind=TRUE)]<-"red"
  siteDrawCol[which(siteMean < -0.4, arr.ind=TRUE)]<-"blue"

  # Build matrix of "significance" for corrplot
  siteDraw <- siteDrawCol
  siteDraw[which(!is.na(siteDraw), arr.ind = TRUE)] <- 0
  siteDraw[which(is.na(siteDraw), arr.ind = TRUE)] <- 1
  siteDraw <- matrix(as.numeric(siteDraw), nrow = nrow(siteMean), ncol = ncol(siteMean))

  Colour <- colorRampPalette(c("blue", "white", "red"))(200)
  corrplot(siteMean, method = "color", col = Colour, type = "lower",
           diag = FALSE, p.mat = siteDraw, tl.srt = 45, title = corTitle)

}
```

```{r}
# Functions to format data

format_spp <- function(data){
  data %>% 
  map(as_tibble) %>%
  bind_cols() %>%
  rownames_to_column() %>%
  set_names(c("species", "c", "b", "a", "e", "f", "d", "g")) %>%
  transmute(species = species,
            env = a + f + 0.5 * d + 0.5 * g,
            env = ifelse(env < 0, 0, env),
            spa = b + e + 0.5 * d + 0.5 * g,
            spa = ifelse(spa < 0, 0, spa),
            codist = c,
            codist = ifelse(codist < 0, 0, codist),
            r2 = env + spa + codist)
}

rawfractions_species <-function(data){
  data %>% 
  map(as_tibble) %>%
  bind_cols() %>%
  rownames_to_column() %>%
  set_names(c("species", "c", "b", "a", "e", "f", "d", "g")) %>% 
    dplyr::select(species, a, b, c, d, e, f, g)
}

format_sites <- function(data){
  
    nspp <- 7
    c <- rowSums(data$overlap1[,,1])/nspp
    b <- rowSums(data$overlap1[,,2])/nspp
    a <- rowSums(data$overlap1[,,3])/nspp

    e <- rowSums(data$overlap2[,,1])/nspp
    f <- rowSums(data$overlap2[,,2])/nspp
    d <- rowSums(data$overlap2[,,3])/nspp

    g <- rowSums(data$overlap3)/nspp

    env <- a + f + 1/2 * d + 1/2 * g
    env <- ifelse(env < 0, 0, env)
    spa <- b + e + 1/2 * d + 1/2 * g
    spa <- ifelse(spa < 0, 0, spa)
    random <- c
    codist <- ifelse(random < 0, 0, random)
    r2 <- env + spa + codist

    sitedata <- cbind.data.frame(env, spa, codist, r2)
    return(sitedata)
}

rawfractions_sites <- function(data){
  
    nspp <- 7
    c <- rowSums(data$overlap1[,,1])/nspp
    b <- rowSums(data$overlap1[,,2])/nspp
    a <- rowSums(data$overlap1[,,3])/nspp

    e <- rowSums(data$overlap2[,,1])/nspp
    f <- rowSums(data$overlap2[,,2])/nspp
    d <- rowSums(data$overlap2[,,3])/nspp

    g <- rowSums(data$overlap3)/nspp

    sitedata <- cbind.data.frame(a,b,c,d,e,f,g) %>% 
      mutate(site = 1:36)
    return(sitedata)
}
```

```{r}
# functions for testing convergence
get_mcmc_obj <- function(model){
  parameters <- "meansParamX"
  x <- model

  paramMCMCMat <- x$results$estimation[[parameters]]

  ### Name rows and columns of matrix
  rownames(paramMCMCMat) <- rownames(x$results$estimation[[parameters]])
  colnames(paramMCMCMat) <- colnames(x$results$estimation[[parameters]])

  paramBurnMCMC <- x$results$burning[[parameters]]
  rownames(paramBurnMCMC) <- rownames(x$results$burning[[parameters]])
  colnames(paramBurnMCMC) <- colnames(x$results$burning[[parameters]])
  paramMCMCMat <- rbind(paramBurnMCMC,paramMCMCMat)

  thinSet <- as.numeric(sub("iter", "", rownames(paramMCMCMat)[1:2]))
  modelThin <- thinSet[2] - thinSet[1]

  result <- mcmc(data = paramMCMCMat, thin = modelThin)
}

```

So, with Guillaume's HMSC version, we can only use probit as the link function to the model, which restricts this to only using presence absence data. Each set of figures corresponds to one type of landscape

### Reminder of what the landscapes look like  

```{r fig.height=6, fig.width=6}
resetarits_data %>%
  filter(type == "E") %>% 
  mutate(type = case_when(type == "A" ~ "Low/rare removal",
                          type == "B" ~ "Low/common removal",
                          type == "C" ~ "High/common removal",
                          type == "D" ~ "High/rare removal",
                          type == "E" ~ "Control, no removal"),
         habitat = ifelse(habitat == "C", "Algae", "Bacteria")) %>% 
  ggplot(., aes(x = x.value, y = y.value, color = habitat)) +
  facet_wrap(~landscape, ncol = 2) +
  # facet_grid(landscape~type, switch = "y")+
  geom_segment(aes(x = 1, xend = 1, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 2, xend = 2, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 3, xend = 3, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 4, xend = 4, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 5, xend = 5, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 6, xend = 6, y = 1, yend = 6), color = "black") +
  geom_segment(aes(x = 1, xend = 6, y = 3, yend = 3), color = "black") +
  geom_point(size = 4) +
  scale_color_manual(values = c("#a6de52", "#b652de")) +
  scale_x_continuous(limits = c(0.5, 6.5), breaks = c(1:6), label = c(1:6)) +
  scale_y_continuous(limits = c(0.5, 6.5), breaks = c(1:6), label = c(1:6)) +
  labs(title = "Control metacommunity",
       x = "x position",
       y = "y postition") +
  guides(color = guide_legend(title = "Habitat type")) +
  theme_bw()
```

### Landscape 1

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 1

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```

```{r}
# save data for plots later:

rawvpspp <- rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))

rawvpsites <- rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))

```

### Landscape 2  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 2

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```

```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 3  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 3

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```



```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```


### Landscape 4

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 4

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```


```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 5  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 5

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```



```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 6  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 6

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```


```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 7

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 7

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```


```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```
### Landscape 8  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 8

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```



```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 9  

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 9

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```

```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

### Landscape 10

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}

lans_num <- 10

onectrl <- ctrl_density %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape) %>%
  as.matrix()

onectrl[onectrl > 0] <- 1

env_vars <- ctrl_env %>%
  dplyr::filter(., landscape==lans_num) %>%
  dplyr::select(., -landscape)

ashmsc <- as.HMSCdata(Y = onectrl, X = cbind(env_vars, ctrl_mem),
                      Random = as.factor(1:36),
                      scaleX = TRUE, interceptX = TRUE)
niter <- 3000
nburn <- 1000
thin <- 2

m1 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)
m2 <- hmsc(ashmsc, family = "probit", niter = niter, nburn = nburn, thin = thin)


model <- list(get_mcmc_obj(m1), get_mcmc_obj(m2))

# Variation Partitioning
vpsppm1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)
vpsppm2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)),
                  type = "III", R2adjust = TRUE)

vpsitem1 <- variPart(m1, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)
vpsitem2 <- variPart(m2, groupX = c(rep("env",3),rep("spa",14)), indSite = TRUE,
                  type = "III", R2adjust = TRUE)


```

```{r eval=FALSE}
# Diagnostics
gelman.diag(model)
gelman.plot(model)
traceplot(model)
```


```{r}
# Format the data and plot

sppdat <- format_spp(vpsppm1) %>% 
  mutate(chain = "c1") %>% 
  bind_rows(format_spp(vpsppm2) %>% 
              mutate(chain = "c2"))

species_plot(sppdat, plotMain = paste("Landscape", lans_num), colorVar = "chain", colorLegend = "Chain")

sitedat <- format_sites(vpsitem1) %>% 
  mutate(chain = "c1") %>% 
  bind_cols(env_vars) %>% 
  bind_rows(format_sites(vpsitem2) %>% 
              mutate(chain = "c2") %>%
              bind_cols(env_vars))

sites_plot(sitedat, colorVar = "chain", plotMain = "Sites")


par(mfrow = c(1,2))
interaction_plot(m1)
interaction_plot(m2)
```

```{r}
# save data for plots later:

bind_rows(rawvpspp,
          rawfractions_species(vpsppm1) %>% 
  mutate(chain = "c1",
         landscape = lans_num) %>% 
  bind_rows(rawfractions_species(vpsppm2) %>% 
              mutate(chain = "c2",
                     landscape = lans_num))) -> rawvpspp

bind_rows(rawvpsites,
rawfractions_sites(vpsitem1) %>% 
  mutate(chain = "c1", 
         landscape = lans_num) %>% 
  bind_cols(env_vars) %>% 
  bind_rows(rawfractions_sites(vpsitem2) %>% 
              mutate(chain = "c2", 
         landscape = lans_num) %>%
              bind_cols(env_vars))) -> rawvpsites

```

```{r}
saveRDS(rawvpspp, "raw_fractions_control_species_probit.RDS")
saveRDS(rawvpsites, "raw_fractions_control_sites_probit.RDS")
```

