---
title: "Title for third chapter"
abstract: |
  This should be the abstract
output:
  word_document:
    reference_docx: protists_ref.docx
  html_document:
    df_print: paged
bibliography: protists_hmsc.bib
csl: ecology-letters.csl
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
```



\newpage
# Introduction

## Why do we study animal movement and what can it tell us?
   Movement is a fundamental ecological process, critical to an animal's biology and it's interactions with the environment. The study of animal movement tends to focus on four basic mechanistic questions: the why, when, where, and how, and these questions can be answered at the scales of individuals or populations. A general framework for movement ecology that allows to link movement patterns and processes, starts with a focus on movement itself and the individual's internal state, navigation capacity, motion capacity, and responses to external factors [@nathan2008movement]. The overall goal of studying movement seeks to find the linkages between the causes and mechanisms of animal movement, that result in spatiotemporal patterns that feedback to various ecological and evolutionary processes. 

## What is the importance of individual variation in animal movement?  
  Although there is variation in animal movement at the individual scale, the general focus has been on understanding the typical movement patterns, built around average measures at population levels. This focus on generality has driven to a lack of frameworks for understanding variation, how it is maintained, and the consequences of this variation across populations, communities, and ecosystems. Although there have been recent calls for incorporating individual variation in movement [@snell2019consequences, @shaw2020causes] we still need to develop theory that explores different types of variation in movement patterns to understand its consequences across these levels. In particular, when considering species interactions, incorporating individual variation becomes essential to understand how positive or negative feedback loops play into the maintenance of variation in movement as individuals respond to external factors in their environment [@shaw2020causes].  
  
## How does this relate to mutualisms and long-distance movements?
  The specific case of seed dispersal is interesting because of the different levels and interactions happening. At the individual level, we focus on an individual bird consuming fruit and dispersing the seeds of the tree. How this particular individual moves across the landscape directly affects the dispersal for that specific tree and other trees from which it consumes fruit. At the same time, that individual has intra-individual variation in movement patterns associated to specific events in that individual's lifetime, such as breeding and nesting, or even smaller scale variation related to different states, such as foraging or resting. Interspecific interactions come at play as multiple species find themselves together feeding from the same tress, and thus competing for these resources, while at the same time intraspecific interactions due to social behavior broadly determine general movement patterns. From the plant's perspective, the variation in movement patterns across all dispersers will determine eventual plant population spatial spread and success. Individuals will vary in their distances traveled while foraging or searching, directly influencing seed dispersal for the plant. Individuals with a tendency to travel larger distances or with higher probabilities of long-distance movements, will have a larger impact on plant population dynamics by increasing the plant's long-distance dispersal. These long-distance movements for seed-dispersing animals, or long-distance dispersal events for plants, can lead to spatial sorting of populations and range expansions [These are sources I haven't finished reading yet: Shine2011PNAS, Philips2008AmNat, Riotte-Lambert2019Trends.] This is also the case for pollination, where pollinator variability in movement patterns and long-distance movements has direct implications for pollination success and plant population persistence, specially in fragmented landscapes [need to find sources for this]. 
  Shaw makes references to how interspecific interactions can contribute to individual movement variation in parasite/pathogen systems. In my case, I would consider how presence of other competitive frugivores could influence this variation (Competition between toucans for the virola fruits and space. Larger aracari kick out the little ones [@holbrook2011home]). Shaw brings up how worse conditions can cause increased movement for searching better habitats and escape from these areas.

## What will this paper actually do to address the main question?  
  In this paper we would like to present a statistical framework that incorporates variability among individuals into population level movement patterns. Providing theoretical frameworks that incorporate individual variation in animal movement can help us link that variation to seed dispersal patterns, and in particular to range expansion dynamics, having consequences at the landscape and regional scales. We will also explore how the variation in long-distance movements translates to population level estimates and how these long-distance movements or deviations from typical movement patterns can be incorporated into this framework.Although it increases the complexity and requires more fine scale data, the framework recognizes how variation at the level of individuals can have consequences at larger ecological scales. In this regard, state-space models (SSMs) have been suggested as flexible options to describe the general framework that incorporates observation error and noisy data, as it is common in the case of radiotelemetry data, and even the use of hierarchical structures or mixed-effects SSMs that can explicitly model variability across individuals [@patterson2008state]. With our work, we seek to expand on the use of state-space models that incorporate variability in movement and can later be used to simulate movement patterns that affect seed dispersal or pollination patterns at the landscape scale.


# Methods  

## Overview of state-space models for movement  
  State-space models provide a probabilistic framework that allow for prediction of future states of a system based from previous states, by coupling an observation model with an underlying mechanistic model. When extending this framework to movement ecology, we understand that the process model provides the mechanism for movement across space and time, and the observation model is related to the sampling process. In movement data, a state-space process allows us to couple a statistical model for the observation method, accounting for errors in sampling or detection, with a separate model for the movement dynamics which are determined by the effects of behavior or responses to the environment [@patterson2008state]. In general, state-space models are used to identify different states, or behavioral states, that determine different movement patterns associated to step length and turning angle. And some of the main questions asked with this approach are related to identifying these different states, or behavioral state-switching, from time series data on location tracking.HMMs can be used to categorize this movement data into behavioral states, and link it to foraging or mating activity, as an example.
  
  The moveHMM package allows for fitting hmm models to different time series, which can come from different individuals, assuming that all individuals share the same movement models, meaning the same distributions and parameters for step length and angle. This is referred to as 'complete pooling' [@langrock2012flexible, @michelot2016movehmm], but there is no current implementation for fitting HMMs to highly irregular and noisy tracking data, that explicitly incorporates variability among individuals. In this paper, we would like to show the effects of incorporating individual variability under a HMM framework that allows for variation not only in parameter values associated to udnerlying model distributions of step length and angle, but also on overall distribution function.

# References






